# Generated by Django 3.2.9 on 2021-11-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('a', models.CharField(max_length=50)),
                ('a_right', models.BooleanField()),
                ('b', models.CharField(max_length=50)),
                ('b_right', models.BooleanField()),
                ('c', models.CharField(max_length=50)),
                ('c_right', models.BooleanField()),
                ('d', models.CharField(max_length=50)),
                ('d_right', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='')),
                ('questions', models.ManyToManyField(to='main.Question')),
            ],
        ),
    ]
