# Generated by Django 3.2.9 on 2021-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
